<a href="https://colab.research.google.com/github/SimreAniri/NLP/blob/main/Lesson_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.tokenize.treebank import TreebankWordDetokenizer
from nltk.corpus import stopwords

import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)
import os

In [26]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

from sklearn import model_selection, preprocessing, linear_model

Загрузим данные после обработки и токенизации

In [3]:
data = pd.read_pickle('combine_df.pkl')

In [4]:
data.head()

id  ...                                   tweet_lemmatized
0   1  ...  [when, father, is, dysfunctional, and, is, so,...
1   2  ...  [thanks, for, lyft, credit, can, not, use, cau...
2   3  ...                            [bihday, your, majesty]
3   4  ...  [model, love, you, take, with, you, all, the, ...
4   5  ...             [factsguide, society, now, motivation]

[5 rows x 7 columns]

1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и tweet_lemmatized' отдельно.

Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.

Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
Исключим стоп-слова с помощью stop_words='english'. 

Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().


In [5]:
twd = TreebankWordDetokenizer()
doc_stemmed = data['tweet_stemmed'].apply(lambda x: twd.detokenize(x))
doc_stemmed

0        when father is dysfunct and is so selfish he d...
1        thank for lyft credit cannot use caus they do ...
2                                      bihday your majesti
3          model love you take with you all the time in ur
4                              factsguid societi now motiv
                               ...                        
49154    thought factori left right polaris trump usele...
49155    feel like mermaid hairflip neverreadi formal w...
49156    hillari campaign today in ohio omg amp use wor...
49157    happi at work confer right mindset lead to cul...
49158    my song so glad free download shoegaz newmus n...
Name: tweet_stemmed, Length: 49159, dtype: object

In [19]:
count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', binary=True, max_df=0.9, max_features = 1000)

# Создаем the Bag-of-Words модель
count_bag_of_words_stemmed = count_vectorizer.fit_transform(doc_stemmed)

# Отобразим Bag-of-Words модель как DataFrame
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(count_bag_of_words_stemmed.toarray(), columns = feature_names)

abl  about  absolut  accept  account  ...  young  your  yourself  youtub  yr
0        0      0        0       0        0  ...      0     0         0       0   0
1        0      0        0       0        0  ...      0     0         0       0   0
2        0      0        0       0        0  ...      0     1         0       0   0
3        0      0        0       0        0  ...      0     0         0       0   0
4        0      0        0       0        0  ...      0     0         0       0   0
...    ...    ...      ...     ...      ...  ...    ...   ...       ...     ...  ..
49154    0      0        0       0        0  ...      0     0         0       0   0
49155    0      0        0       0        0  ...      0     0         0       0   0
49156    0      0        0       0        0  ...      0     0         0       0   0
49157    0      0        0       0        0  ...      0     0         0       0   0
49158    0      0        0       0        0  ...      0     0         0       0   0

[49159 rows x 1000 columns]

In [10]:
doc_lemmatized = data['tweet_lemmatized'].apply(lambda x: twd.detokenize(x))
doc_lemmatized

0        when father is dysfunctional and is so selfish...
1        thanks for lyft credit cannot use cause they d...
2                                      bihday your majesty
3          model love you take with you all the time in ur
4                        factsguide society now motivation
                               ...                        
49154    thought factory left right polarisation trump ...
49155    feeling like mermaid hairflip neverready forma...
49156    hillary campaigned today in ohio omg amp used ...
49157    happy at work conference right mindset lead to...
49158    my song so glad free download shoegaze newmusi...
Name: tweet_lemmatized, Length: 49159, dtype: object

In [20]:
count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', binary=True, max_df=0.9, max_features = 1000)

# Создаем the Bag-of-Words модель
count_bag_of_words_lemmatized = count_vectorizer.fit_transform(doc_lemmatized)

# Отобразим Bag-of-Words модель как DataFrame
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(count_bag_of_words_lemmatized.toarray(), columns = feature_names)

able  about  absolutely  account  ...  yourself  youtube  yr  yummy
0         0      0           0        0  ...         0        0   0      0
1         0      0           0        0  ...         0        0   0      0
2         0      0           0        0  ...         0        0   0      0
3         0      0           0        0  ...         0        0   0      0
4         0      0           0        0  ...         0        0   0      0
...     ...    ...         ...      ...  ...       ...      ...  ..    ...
49154     0      0           0        0  ...         0        0   0      0
49155     0      0           0        0  ...         0        0   0      0
49156     0      0           0        0  ...         0        0   0      0
49157     0      0           0        0  ...         0        0   0      0
49158     0      0           0        0  ...         0        0   0      0

[49159 rows x 1000 columns]

2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.

Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.

Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
Исключим стоп-слова с помощью stop_words='english'.

Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().


In [21]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.9, max_features = 1000, stop_words='english')
tfidf_vector_stemmed = tfidf_vectorizer.fit_transform(doc_stemmed)

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(tfidf_vector_stemmed.toarray(), columns = feature_names)

abl  absolut  accept  account  act  ...  york  young  youtub   yr  yummi
0      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
1      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
2      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
3      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
4      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
...    ...      ...     ...      ...  ...  ...   ...    ...     ...  ...    ...
49154  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
49155  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
49156  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
49157  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
49158  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0

[49159 rows x 1000 columns]

In [22]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.9, max_features = 1000, stop_words='english')
tfidf_vector_lemmatized = tfidf_vectorizer.fit_transform(doc_lemmatized)

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(tfidf_vector_lemmatized.toarray(), columns = feature_names)

able  absolutely  account  act  action  ...  york  young  youtube   yr  yummy
0       0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0
1       0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0
2       0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0
3       0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0
4       0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0
...     ...         ...      ...  ...     ...  ...   ...    ...      ...  ...    ...
49154   0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0
49155   0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0
49156   0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0
49157   0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0
49158   0.0         0.0      0.0  0.0     0.0  ...   0.0    0.0      0.0  0.0    0.0

[49159 rows x 1000 columns]

3. Создайте мешок слов с помощью sklearn.feature_extraction.text.HashingVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.

Ограничим количество фичей, с помощью n_features = 1000.

Исключим стоп-слова с помощью stop_words='english'.


In [23]:
vectorizer = HashingVectorizer(n_features=1000, stop_words='english')
HashingVector_stemmed = vectorizer.fit_transform(doc_stemmed)
print(HashingVector_stemmed.shape)
print(HashingVector_stemmed.toarray())

(49159, 1000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [24]:
vectorizer = HashingVectorizer(n_features=1000, stop_words='english')
HashingVector_lemmatized = vectorizer.fit_transform(doc_lemmatized)
print(HashingVector_lemmatized.shape)
print(HashingVector_lemmatized.toarray())

(49159, 1000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


4. Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте таблицу метод векторизации и скор который вы получили (в методах векторизации по изменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы


In [16]:
score = pd.DataFrame(columns=['CountVectorizer_stemmed', 'CountVectorizer_lemmatized', 'TfidfVectorizer_stemmed', 'TfidfVectorizer_lemmatized', 'HashingVectorizer_stemmed', 'HashingVectorizer_lemmatized'])
score.head()

Empty DataFrame
Columns: [CountVectorizer_stemmed, CountVectorizer_lemmatized, TfidfVectorizer_stemmed, TfidfVectorizer_lemmatized, HashingVectorizer_stemmed, HashingVectorizer_lemmatized]
Index: []

In [18]:
# Загружаем данные
data = open('corpus').read()
labels, texts = [], []
for i, line in enumerate(data.split("\n")):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))

# создаем df
trainDF = pd.DataFrame()
trainDF['text'] = texts
trainDF['label'] = labels
trainDF.head(5)

text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2
3  Excellent Soundtrack: I truly like this soundt...  __label__2
4  Remember, Pull Your Jaw Off The Floor After He...  __label__2

In [28]:
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(trainDF['text'], trainDF['label'])

# labelEncode целевую переменную
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)


xtrain_count =  count_bag_of_words_stemmed.transform(train_x)
xvalid_count =  count_bag_of_words_stemmed.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions = classifier.predict(xvalid_count)
predictions

AttributeError: ignored